### ISSUE TITLE
Blender 4.0.2 | Adding camera not working

### ISSUE THREAD

**Issue by kents00** [kents00/VyCam#1]
The blender community altered the code format for adding a camera to your scene, resulting in an error. 

Backlogs: 

> Python: Traceback (most recent call last):
>   File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\VyCam\__init__.py", line 103, in execute
>     camera_manager.set_camera_to_point_of_view()
>   File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\VyCam\__init__.py", line 36, in set_camera_to_point_of_view
>     bpy.ops.view3d.camera_to_view(override)
>   File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\bpy\ops.py", line 106, in __call__
>     C_exec, C_undo = _BPyOpsSubModOp._parse_args(args)
>   File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\bpy\ops.py", line 60, in _parse_args
>     raise ValueError("1-2 args execution context is supported")
> ValueError: 1-2 args execution context is supported

**Comment by kents00** [comment]
The code syntax for adding a camera to a scene was changed in the most recent blender release (4.0.2)

Before:
```python
def set_camera_to_point_of_view(self,context):
    for area in bpy.context.screen.areas:
        if area.type == 'VIEW_3D':
            for region in area.regions:
                if region.type == 'WINDOW':
                    override = {'area': area, 'region': region,
                                'edit_object': self.camera_object}
                    bpy.ops.view3d.camera_to_view(override)
    return {'FINISHED'}
```

After
```python
def set_camera_to_point_of_view(self):
    for area in bpy.context.screen.areas:
        if area.type == 'VIEW_3D':
            for region in area.regions:
                if region.type == 'WINDOW':
                    bpy.ops.view3d.camera_to_view()
    return {'FINISHED'}
```
